feat: add grafana datasource for psql
FNNDSC/miniChRIS pull request #15
Opened 2022-11-03 05:50 UTC by sakshi1215

fixes #14

2022-11-09 14:19 UTC, jennydaman requested changes
I don't think it makes sense to mix YAML and INI config syntax.

2022-11-09 14:37 UTC, sakshi1215 commented
I thought I had changed the ini format to yaml syntax but looks like I
missed pushing that commit, let me fix it.

On Wed, 9 Nov 2022 at 19:50, Jennings Zhang ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I don't think it makes sense to mix YAML and INI config syntax.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FNNDSC/miniChRIS-docker/pull/15#pullrequestreview-1174137903>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANF3CEAATHIAGRZZW2HCQITWHOXJRANCNFSM6AAAAAARVY7DYM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-11 16:33 UTC, sakshi1215 commented
@jennydaman It is fixed now, please take a look. Ini & datasources are two different files which can't be merged, idk why I configured it in the helm-chart way where you can merge ini in your values.yaml.

2022-11-14 17:03 UTC, jennydaman requested changes

2022-11-14 17:03 UTC, jennydaman commented on docker-compose.yml
> +      - ./provisionaning:/etc/grafana/provisioning
the dir name contains a typo, would you fix this?

2024-07-27 06:29 UTC, closed without merging